services:
  pytwb-demo:
    image: pytwb-demo-image
    build:
      context: .
      dockerfile: pytwb_ws/Dockerfile
      args:
        ROS_DISTRO: humble
    network_mode: host
    ipc: host
    environment:
      - DISPLAY=:${DISPLAY} # for VSCode config
    volumes:
      - ./pytwb_ws:/root/pytwb_ws:rw
    command: sleep infinity
