services:
  pytwb:
    image: pytwb-demo-image
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: humble
    network_mode: host
    ipc: host
    environment:
      - DISPLAY=:$DISPLAY # for WSL
    volumes:
      - ./pytwb_ws/src/pytwb_demo:/root/pytwb_wb/src/pytwb_demo:rw
    command: sleep infinity

